apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - {{ .Values.clusterIssuer.route53.domainName }}
        dns01:
          route53:
            region: {{ .Values.clusterIssuer.route53.region }}
            hostedZoneID: {{ .Values.clusterIssuer.route53.hostedZoneId | quote }}
